INVIOTCP = prova prova2
prova = <%TCP_send%> header nl "GET " hostname page crnl crnl
prova2 = <%TCP_read%> maskcheck

hostname = schema host
schema = "http://"
host = "ubik/"
page = "index.html"; / %x2020202039140209572095 / "puppalaoooo" / %x87656765878907895760 / %x2222222222222222222222

crnl = cr nl
cr = %x0d
nl = %x0a 

maskcheck = <%ValueCheck%> start size data
start = %d2
size = %d7
data = "DOCTYPE"; / "dOCTYPE"


;data = %x3c2144

header = "HTTP1.1"; / %x2020202020202020202020 / %x000000000000000000000000000000000000000000 / "\\\\\\\\\\\\\\\\\\\\\\\\\\\\" / "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

